In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a=np.array([1,2,3,"A"])
print(a)

['1' '2' '3' 'A']


In [ ]:
a=np.array([1,2,3,12.45])
print(a)

[ 1.    2.    3.   12.45]


In [ ]:
# more than one dimension

a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
#minimum dimension
a=np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [ ]:
a=np.array([1,2,3,4,5],ndmin=2)
print(a.shape)

(1, 5)


In [ ]:
# dtype parameter

a=np.array([1,2,3,4,5],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [ ]:
a=np.array([1,2,3,4,5],dtype=float)
print(a)

[1. 2. 3. 4. 5.]


In [ ]:
n=np.array([[2,3,5],[9,11,7],[3,2,7]])
print(n)

[[ 2  3  5]
 [ 9 11  7]
 [ 3  2  7]]


In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
y=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(y)
z=x+y
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [ ]:
#ND ARRAY SHAPE

a=np.array([[1,2,3],[4,5,6]])
print(a.shape)


(2, 3)


In [ ]:
#this resize the ndarray

a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# numpy also provide a reshape function to resize an array

a=np.array([[1,2,3,],[4,5,6]])
print(a)
print()
b=a.reshape(3,2)
print(b)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a=np.zeros((5),dtype=int)
print(a)

[0 0 0 0 0]


In [ ]:
a=np.array([[2,3,4,5,6],[1,2,4,3,6],[3,4,17,22,7],[3,5,6,7,8],[8,4,2,1,6]])
print(a)

[[ 2  3  4  5  6]
 [ 1  2  4  3  6]
 [ 3  4 17 22  7]
 [ 3  5  6  7  8]
 [ 8  4  2  1  6]]


In [ ]:
#diognal element
a=np.array([[2,3,4,5,6],[1,2,4,3,6],[3,4,17,22,7],[3,5,6,7,8],[8,4,2,1,6]])
print(np.diag(a))

[ 2  2 17  7  6]


In [ ]:
ls=[12,23,14,16,20]
print(np.diag(ls))

[[12  0  0  0  0]
 [ 0 23  0  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 20]]


In [ ]:
ls=[12,23,14,16,20]
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# arange()         # array of range
# Deep copy

ls=[12,24,35,36,45]
ls1=ls.copy()
print(ls)
print(ls1)
ls1[2]="Aashish"
print(ls)
print(ls1)

[12, 24, 35, 36, 45]
[12, 24, 35, 36, 45]
[12, 24, 35, 36, 45]
[12, 24, 'Aashish', 36, 45]


In [ ]:
ls=[[12,24],[35,36]]
ls1=ls.copy()
print(ls)
print(ls1)
ls1[0][1]="Aashish"
print(ls)
print(ls1)

[[12, 24], [35, 36]]
[[12, 24], [35, 36]]
[[12, 'Aashish'], [35, 36]]
[[12, 'Aashish'], [35, 36]]


In [ ]:
import copy
ls=[[12,24],[35,36]]
ls1=copy.deepcopy(ls)
print(ls)
print(ls1)
ls1[0][1]="Aashish"
print(ls)
print(ls1)

[[12, 24], [35, 36]]
[[12, 24], [35, 36]]
[[12, 24], [35, 36]]
[[12, 'Aashish'], [35, 36]]


In [ ]:
#create a matrix

import numpy as np
matrix1=np.array([[1,3],[5,7]])
print(matrix1)
print()

[[1 3]
 [5 7]]



In [ ]:
#metrix transpose

result=np.transpose(matrix1)
print(result)

[[1 5]
 [3 7]]


In [ ]:
#matrix multiplication
#create two matrix

matrix1=np.array([[1,3],[5,7]])
matrix2=np.array([[2,6],[4,8]])


# calculate the dot product of the two matrix

result=np.dot(matrix1, matrix2)
print("matrix1*matrix2: \n",result)



matrix1*matrix2: 
 [[14 30]
 [38 86]]


In [ ]:
matrix5=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(matrix5)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(matrix5[1:3,:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
print(matrix5[0:3,0:3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
# comparison between list and array
# 3 benefits of array
# 1. Take less memory
# 2. fast
# 3. convininent
import time
import sys

sys.getsizeof(10)


28

In [ ]:
l=range(200000)
print(sys.getsizeof(2)*len(l))


5600000


In [ ]:
a=np.arange(200000)
a.itemsize

8

In [ ]:
a=np.arange(200000)
print(a.itemsize*len(a))

1600000


In [ ]:
a1=range(100000)
b1=range(100000)
start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print("time taken:",(time.time()-start)*1000)

time taken: 22.10211753845215


In [ ]:
a2=np.arange(100000)
b2=np.arange(100000)
start=time.time()
c2=a2+b2
print("time taken by array:",(time.time()-start)*1000)

time taken ny array: 4.026889801025391


In [ ]:
time.time()

1717067573.6156485

In [ ]:
#convininent

n1=np.arange(100)
n2=np.arange(100)
n1*n2




array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [ ]:
#numpy linspace
# this function is similar to arange()function. in this function instead of step the number of evenly spaced values between the interval is specified.

import numpy as np
x=np.linspace(10,20,5)
print(x)


[10.  12.5 15.  17.5 20. ]


In [ ]:
# endpoint set to false

x=np.linspace(10,20,5, endpoint=False)
print(x)


[10. 12. 14. 16. 18.]


In [ ]:
# find the restep value

x=np.linspace(1,2,5, retstep=True)
print(x)


(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [ ]:
#numpy hstack() function
# horizontally stack numpy arrays using numpy.hstack()

x=np.array((3,5,7))
print(x)
print()
y=np.array((6,8,9))
print(y)
print()
np.hstack((x,y))


[3 5 7]

[6 8 9]



array([3, 5, 7, 6, 8, 9])

In [ ]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[8],[9]])
print(y)
print()
np.hstack((x,y))

[[3]
 [5]
 [7]]

[[5]
 [8]
 [9]]



array([[3, 5],
       [5, 8],
       [7, 9]])

In [ ]:
#numpy vstack

import numpy as np
x=np.array([3,5,7])
print(x)
print()
y=np.array([5,7,9])
print(y)
print()
np.vstack((x,y))

[3 5 7]

[5 7 9]



array([[3, 5, 7],
       [5, 7, 9]])

In [ ]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[3],[5],[9]])
print(y)
print()
np.vstack((x,y))

[[3]
 [5]
 [7]]

[[3]
 [5]
 [9]]



array([[3],
       [5],
       [7],
       [3],
       [5],
       [9]])

In [ ]:
#numpy conditional selection

import numpy as np
a=np.arange(1,22)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [ ]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [ ]:
a[a==5]

array([5])

In [ ]:
a[a<5]

array([1, 2, 3, 4])

In [ ]:
a[a%2!=0]=0
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20,  0])

In [ ]:
# Generate ramdom integer in numpy
# generate the random integer from 0 to 9

import numpy as np
random_number=np.random.randint(0,10)
print(random_number)

7
